### ISSUE TITLE
tbb::global_control in Embree might affect whole application

### ISSUE THREAD

**Issue by LauraHorst** [RenderKit/embree#507]
It seems like the `static tbb::global_control` object in Embree sometimes affects the rest of the application using Embree.

Unfortunately I haven't been able to construct a simple example, so here is a rough explanation of what is happening in our application:

There are several `tbb::task_arena`s in our code which are given a parameter setting their maximum amount of threads. In between there is Embree code running. Sometimes when `tbb::task_arena`s are supposed to run single threaded they instead run multi threaded, but only if Embree code has run before.

So far I haven't been able to find the exact cause. The parameters for the `tbb::task_arena`s are set correctly at all times. Setting `tbb::global_control` before creating the `RTCDevice` leads to the original/desired behaviour of the following `tbb::task_arena.` Because `tbb::global_control` only has an effect during its lifetime, my guess is that the `static` one in Embree might mess up the rest of the application.

Thread counts behave as desired with TBB v2021.5.0 (interface version 12050) and Embree v3.13.4.
With TBB v2021.13.0 (Interface version 12130) thread counts misbehave, both with Embree v3.13.4 and v4.3.3. Since it only seems to happen in combination with Embree I'm quite sure that it's an Embree problem nonetheless.

This affects both Windows and Linux (WSL).

_Edit: `tbb::global_control` must be set earlier._

**Comment by dopitz** [comment]
I tried to reproduce this issue and it turns out this is only a problem, if you specify a thread count to embree during device creation (with `threads=[int]`). 

If you do not do this embree will not create a `tbb::global_control` obejct and should not interfere with your application code. 

Does this resolve your issue?

**Comment by dopitz** [comment]
`tbb::global_control` was introduced with some new version of TBB. `embree` tries to support older TBB versions as well and if it is compiled with an old enough TBB, we skip the whole `tbb::global_control` creation. So unfortunately the "broken" behavior in this instance is probably the one to stay for future TBB and embree versions.

**Comment by LauraHorst** [comment]
Turns out it was this TBB bug: https://github.com/uxlfoundation/oneTBB/issues/1417
